# Generated by Django 2.0.4 on 2018-04-23 19:37

import crawlers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0003_auto_20180417_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.TextField()),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawlers.Crawler')),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='crawler',
        ),
        migrations.AddField(
            model_name='result',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='error_message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='data',
            field=models.FileField(upload_to=crawlers.models.crawler_result_path),
        ),
        migrations.AddField(
            model_name='result',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crawlers.Profile'),
            preserve_default=False,
        ),
    ]
