# Generated by Django 2.0.4 on 2018-04-26 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0004_auto_20180423_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='profile',
        ),
        migrations.AddField(
            model_name='result',
            name='crawler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crawlers.Crawler'),
            preserve_default=False,
        ),
    ]
